import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'app.dart';
import 'data/models/child_profile.dart';
import 'data/models/kingdom_state.dart';
import 'data/models/lesson_progress.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();

  // Register adapters (these will be generated by hive_generator)
  Hive.registerAdapter(ChildProfileAdapter());
  Hive.registerAdapter(KingdomStateAdapter());
  Hive.registerAdapter(KingdomItemAdapter());
  Hive.registerAdapter(LessonProgressAdapter());

  // Open boxes
  await Hive.openBox<ChildProfile>('profiles');
  final kingdomsBox = await Hive.openBox<KingdomState>('kingdoms');
  if (kingdomsBox.get('current') == null) {
    await kingdomsBox.put('current', KingdomState.empty());
  }
  await Hive.openBox<LessonProgress>('progress');

  runApp(
    const ProviderScope(child: MathKingdomApp()),
  );
}