import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'app.dart';
import 'core/localization/app_locale_config.dart';
import 'data/models/child_profile.dart';
import 'data/models/kingdom_state.dart';
import 'data/models/lesson_progress.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();
  await AppLocaleConfig.ensureLoaded();
  await Hive.initFlutter();

  // Register adapters (these will be generated by hive_generator)
  Hive.registerAdapter(ChildProfileAdapter());
  Hive.registerAdapter(KingdomStateAdapter());
  Hive.registerAdapter(KingdomItemAdapter());
  Hive.registerAdapter(LessonProgressAdapter());

  // Open boxes
  await Hive.openBox<ChildProfile>('profiles');
  final kingdomsBox = await Hive.openBox<KingdomState>('kingdoms');
  if (kingdomsBox.get('current') == null) {
    await kingdomsBox.put('current', KingdomState.empty());
  }
  await Hive.openBox<LessonProgress>('progress');

  runApp(
    EasyLocalization(
      supportedLocales: AppLocaleConfig.supportedLocales,
      path: AppLocaleConfig.translationsPath,
      fallbackLocale: AppLocaleConfig.fallbackLocale,
      useOnlyLangCode: true,
      saveLocale: true,
      useFallbackTranslations: true,
      child: const ProviderScope(child: MathKingdomApp()),
    ),
  );
}
